# Generated by Django 5.1.5 on 2025-01-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_ad_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ad',
            name='tags',
        ),
        migrations.AddField(
            model_name='ad',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='ads', to='ads.tag'),
        ),
    ]
