# Generated by Django 5.1.5 on 2025-01-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_tag_remove_ad_tags_ad_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='ads', to='ads.tag'),
        ),
    ]
